
export const metadata = {
  title: 'Vinoth Thulukanam',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      {/* <body className={inter.className}>{children}</body> */}
      <body>
        {/* <Provider> */}
        {children}
        {/* </Provider> */}
      </body>
    </html>
  )
}
